version: '3.7'

services: 
  influxdb:
      image: influxdb
      ports:
        - "${INFLUX_PORT}:8086"
      networks:
        - logs
       
  influxdb_cli:
      image: influxdb
      entrypoint: influx setup --bucket ${BUCKET_NAME} -t ${TOKEN} -o ${ORG} --username=${INFLUX_USERNAME} --password=${PASSWORD} --host ${HOST} -f
      restart: on-failure:10
      networks:
        - logs
      depends_on:
        - influxdb
        
  telegraf:
      image: telegraf
      env_file:
        - ./.env
      volumes:
        - ./my-conf.conf:/etc/telegraf/telegraf.conf
      networks:
        - kanban
        - logs
      depends_on:
        - influxdb_cli
      restart: on-failure:10

networks:
  logs:
    driver: bridge
    name: logs 
# if your are not using kanban gateway to deploy the application
# just comment all the kanban network references in this docker-compose file ..
  kanban:
    driver: overlay
    external: 
      name: eg-gateway_kanban
            