version: '3.7'

services: 
  rabbit-mq:
      image: rabbitmq:3-management
      hostname: any_rabbit
      ports: 
        - "15672:15672"
        - "5672:5672"
      networks:
        - logs

  influxdb:
      image: influxdb
      ports:
        - "${INFLUX_PORT}:8086"
      networks:
        - logs
       
  influxdb_cli:
      image: influxdb
      entrypoint: influx setup --bucket ${BUCKET_NAME} -t ${TOKEN} -o ${ORG} --username=${INFLUX_USERNAME} --password=${PASSWORD} --host ${HOST} -f
      restart: on-failure:10
      networks:
        - logs
      depends_on:
        - influxdb
        
  telegraf:
      image: telegraf
      environment:
        - BUCKET_NAME=${BUCKET_NAME}
        - ORG=${ORG}
        - TOKEN=${TOKEN}
        - HOST=${HOST}
        - RABBIT_USERNAME=${RABBIT_USERNAME}
        - RABBIT_PASSWORD=${RABBIT_PASSWORD}
        - RABBIT_HOST=${RABBIT_HOST}
        - RABBIT_EXCHANGE=${RABBIT_EXCHANGE}
        - QUEUE=${QUEUE}
      volumes:
        - ./my-conf.conf:/etc/telegraf/telegraf.conf
      networks:
        - logs
      depends_on:
        - influxdb_cli
      restart: on-failure:10

networks:
  logs:
    driver: bridge
    name: logs 